#!/usr/bin/sh

VENV_DIR=${VENV_DIR-$HOME/.venvs}
VENV_ENVAR_DIR=${VENV_ENVAR_DIR-$HOME/.env_vars}
DIR=${PWD##*/}
PY=python3

create() {
    virtualenv --python=$PY $VENV_DIR/$DIR

    mkdir -p $VENV_ENVAR_DIR/$DIR
    touch $VENV_ENVAR_DIR/$DIR/onact
    touch $VENV_ENVAR_DIR/$DIR/onexit

}

# Make the virtual environment source the project virtual environment on 
# activate and unset them on deactivate
setup () {
    echo -e '\n# Source the project environment variables when the venv is activated'>> $VENV_DIR/$DIR/bin/activate
    echo 'source '"$VENV_ENVAR_DIR/$DIR"'/onact' >> $VENV_DIR/$DIR/bin/activate
    sed -i '
        /deactivate ()/,/^}$/ {
        /^}$/ i\
    \n    # Unset the environment variables when deactivating the venv\
    \source '"$VENV_ENVAR_DIR/$DIR"'/onexit
    }
    ' $VENV_DIR/$DIR/bin/activate
}

post_setup() {
    actenv $DIR && [ $DIR == ${PWD##*/} ] && installreqs
}


while getopts d:p: opt; do
    case $opt in
        d) DIR=$OPTARG ;;
        p) PY=$OPTARG ;;
        *) exit 1 ;;
    esac
done


create && setup && post_setup
