#!/usr/bin/env sh

VENV_DIR=${VENV_DIR-$HOME/.venvs}
VENV_ENVAR_DIR=${VENV_ENVAR_DIR-$HOME/.env_vars}
DIR=${1:-${PWD##*/}}

[ -d $VENV_DIR/$DIR ] \
    && echo "Deleting virtual environment $DIR" \
    && rm -r $VENV_DIR/$DIR

[ -d $VENV_ENVAR_DIR/$DIR ] \
    && echo "Deleting $DIR environment variables" \
    && rm -r $VENV_ENVAR_DIR/$DIR


